management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG
spring:
  data:
    mongodb:
      uri: mongodb://localhost:29510/turms-dev
turms:
  ip:
    use-local-ip: true
  storage:
    minio:
      retry:
        enabled: false