management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG
spring:
  profiles:
    include: dev-latest
turms:
  load-balancing:
    advertise-strategy: local_address
  mock:
    enabled: true
  database:
    mongo-properties:
      default-properties:
        auto-index-creation: true
        uri: mongodb://localhost:29510/turms-dev
turms-plugin:
  minio:
    retry:
      enabled: false