logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: debug
spring:
  profiles:
    include: test-latest
turms:
  database:
    mongo-properties:
      default-properties:
        auto-index-creation: true
        uri: mongodb://localhost:29510/turms-test