server:
  error:
    whitelabel:
      enabled: false
  port: 9510 #9510
spring:
  application:
    name: turms
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:29510/turms
      repositories:
        type: reactive
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      fail-on-empty-beans: false
    default-property-inclusion: non_null
    time-zone: UTC
  profiles:
    include: dev,turms
  hazelcast:
    config: classpath:hazelcast.yaml
  boot:
    admin:
      client:
        auto-deregistration: true
        url: http://localhost:9514
        username: turms
        password: turms
        register-once: false
  webflux:
    date-format: yyyy-MM-dd'T'HH:mm:ssX
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    hazelcast:
      enabled: false
logging:
  file:
    name: ../logs/turms.log
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS,UTC
