# HTTP(S) configuration
server:
  port: 8510 #9510
  ssl:
    enabled: false # Enable SSL if needed. Make sure to mutate HTTP requests to HTTPS requests, or Netty will throw NotSslRecordException
    key-store: classpath:keystore-test.p12 # keytool -genkeypair -keyalg RSA -keysize 2048 -validity 3650 -alias turms -keystore keystore-test.p12 -storetype PKCS12 -storepass imturms
    key-store-type: PKCS12
    key-store-password: imturms
    key-alias: turms
  address: 0.0.0.0

spring:
  application:
    name: turms
  jackson:
    deserialization:
      fail-on-unknown-properties: false
      accept-single-value-as-array: true
    serialization:
      fail-on-empty-beans: false
    default-property-inclusion: non_null
    time-zone: UTC
    mapper:
      propagate-transient-marker: true
  profiles:
    include: dev
  hazelcast:
    config: classpath:hazelcast.yaml
  boot:
    admin:
      client:
        auto-deregistration: true
        url: http://localhost:9514
        username: turms
        password: turms
        register-once: false
  webflux:
    format:
      date-time: yyyy-MM-dd'T'HH:mm:ssX
  codec:
    max-in-memory-size: 64KB
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
    - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
management:
#  metrics:
#    enable:
#      prometheus: false
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  file:
    name: ../logs/turms.log
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS,UTC
springfox:
  documentation:
    enabled: true

############################### Turms ###############################

turms:
  cluster:
    node:
      version: @project.version@
    id: turms
    discovery:
      client-ssl:
        enabled: false # Enable SSL if needed
        enabled-protocols: TLSv1.2,TLSv1.3
        key-store: classpath:keystore-test.p12 # keytool -genkeypair -keyalg RSA -keysize 2048 -validity 3650 -alias turms -keystore keystore-test.p12 -storetype PKCS12 -storepass imturms
        key-store-type: PKCS12
        key-store-password: imturms
        key-alias: turms
      server-ssl:
        enabled: false # Enable SSL if needed
        enabled-protocols: TLSv1.2,TLSv1.3
        key-store: classpath:keystore-test.p12 # keytool -genkeypair -keyalg RSA -keysize 2048 -validity 3650 -alias turms -keystore keystore-test.p12 -storetype PKCS12 -storepass imturms
        key-store-type: PKCS12
        key-store-password: imturms
        key-alias: turms
  service:
    database:
      mongo-properties:
        default-properties:
          uri: mongodb://localhost:29510/turms
    message:
      check-if-target-active-and-not-deleted: false
  gateway:
    session:
      enable-authentication: false
#turms-plugin:
#  mock:
#    enabled: true