turms:
  gateway:
    client-api:
      logging:
        included-request-categories:
          - category: all
      return-reason-for-server-error: true
    database:
      mongo-properties:
        user:
          uri: mongodb://localhost:29510/turms-dev