# https://codecentric.github.io/spring-boot-admin/current/
# https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html
server:
  port: 9514
spring:
  boot:
    admin:
      notify:
        mail:
          from: noreply@foo.com
          to: admin@example1.com,admin@example2.com
      ui:
        brand: "<img src='assets/img/icon-spring-boot-admin.svg'><span>Turms APM</span>"
        title: "Turms APM"
#  mail:
#    host: smtp.example.com
#    password: smtp_password
#    username: smtp_user
  security:
    user:
      name: turms
      password: turms